// ARQUIVO GERADO por database/scripts/gerar_seed_uf_populacao.py — NÃO editar à mão.
// Idempotente: rodar de novo atualiza (upsert), não duplica.
// No NoSQLBooster: selecione o banco da OPP na conexão e execute este script.
// Para mirar um banco específico, troque a linha abaixo por:
//   const database = db.getSiblingDB('opp')
const database = db


// --- 1) Catálogo: uf-populacao (seção estadual) ---
const indicators = [
  {"_id": "uf-populacao", "label": "População total", "referenceYear": "2025", "unit": "habitantes", "description": "População residente estimada na Paraíba. Serve também de denominador para as comparações per capita dos demais indicadores estaduais.", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "sourceDataset": "ibge_populacao_observatorio_sebrae", "placements": [{"section": "estadual", "order": 5}]},
]
database.indicators.bulkWrite(indicators.map(i => ({ replaceOne: {
  filter: { _id: i._id }, replacement: i, upsert: true,
} })), { ordered: false })
print(`indicators(estadual) -> ok (${indicators.length} docs)`)

// --- 2) Valores por UF × ano (25 docs) ---
// breakdown.posicao aqui e ordem de tamanho entre as 27 UFs, nao classificacao —
// e por isso nao e normalizada. Sem threshold, como todos os indicadores estaduais.
const values = [
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.468.594", "numericValue": 3468594, "referenceYear": "2001", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.494.893", "numericValue": 3494893, "referenceYear": "2002", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.76, "previousValue": 3468594, "previousYear": "2001", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.518.595", "numericValue": 3518595, "referenceYear": "2003", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.68, "previousValue": 3494893, "previousYear": "2002", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.568.350", "numericValue": 3568350, "referenceYear": "2004", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 1.41, "previousValue": 3518595, "previousYear": "2003", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.595.886", "numericValue": 3595886, "referenceYear": "2005", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.77, "previousValue": 3568350, "previousYear": "2004", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.623.215", "numericValue": 3623215, "referenceYear": "2006", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.76, "previousValue": 3595886, "previousYear": "2005", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "0", "numericValue": 0, "referenceYear": "2007", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": -100.0, "previousValue": 3623215, "previousYear": "2006", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.742.604", "numericValue": 3742604, "referenceYear": "2008", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.769.977", "numericValue": 3769977, "referenceYear": "2009", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.73, "previousValue": 3742604, "previousYear": "2008", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "0", "numericValue": 0, "referenceYear": "2010", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": -100.0, "previousValue": 3769977, "previousYear": "2009", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.791.315", "numericValue": 3791315, "referenceYear": "2011", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.815.171", "numericValue": 3815171, "referenceYear": "2012", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.63, "previousValue": 3791315, "previousYear": "2011", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.914.421", "numericValue": 3914421, "referenceYear": "2013", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 2.6, "previousValue": 3815171, "previousYear": "2012", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.943.885", "numericValue": 3943885, "referenceYear": "2014", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.75, "previousValue": 3914421, "previousYear": "2013", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.972.202", "numericValue": 3972202, "referenceYear": "2015", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 13, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.72, "previousValue": 3943885, "previousYear": "2014", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.999.415", "numericValue": 3999415, "referenceYear": "2016", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.69, "previousValue": 3972202, "previousYear": "2015", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "4.025.558", "numericValue": 4025558, "referenceYear": "2017", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.65, "previousValue": 3999415, "previousYear": "2016", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "3.996.496", "numericValue": 3996496, "referenceYear": "2018", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": -0.72, "previousValue": 4025558, "previousYear": "2017", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "4.018.127", "numericValue": 4018127, "referenceYear": "2019", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 15, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.54, "previousValue": 3996496, "previousYear": "2018", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "4.039.277", "numericValue": 4039277, "referenceYear": "2020", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 15, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.53, "previousValue": 4018127, "previousYear": "2019", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "4.059.905", "numericValue": 4059905, "referenceYear": "2021", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 15, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.51, "previousValue": 4039277, "previousYear": "2020", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "0", "numericValue": 0, "referenceYear": "2022", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": -100.0, "previousValue": 4059905, "previousYear": "2021", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "0", "numericValue": 0, "referenceYear": "2023", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "4.145.040", "numericValue": 4145040, "referenceYear": "2024", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}},
  {"uf": "25", "indicatorId": "uf-populacao", "rawValue": "4.164.468", "numericValue": 4164468, "referenceYear": "2025", "source": "IBGE — estimativas populacionais (cubo IBGE, PIB Municipal), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br)", "isFictional": false, "breakdown": {"posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}, "nota": "posicao e ordem de TAMANHO (14o = 14a UF mais populosa), nao desempenho"}, "variation": {"deltaPct": 0.47, "previousValue": 4145040, "previousYear": "2024", "basis": "yoy"}},
]
const now = new Date()
const ops = values.map(v => ({ updateOne: {
  filter: { uf: v.uf, indicatorId: v.indicatorId, referenceYear: v.referenceYear },
  update: { $set: Object.assign({}, v, { updatedAt: now }) },
  upsert: true,
} }))
const res = database.stateValues.bulkWrite(ops, { ordered: false })
print(`stateValues -> upserted=${res.upsertedCount} modified=${res.modifiedCount} matched=${res.matchedCount}`)
