// ARQUIVO GERADO por database/scripts/gerar_seed_uf_enem.py — NÃO editar à mão.
// Idempotente: rodar de novo atualiza (upsert), não duplica.
// No NoSQLBooster: selecione o banco da OPP na conexão e execute este script.
// Para mirar um banco específico, troque a linha abaixo por:
//   const database = db.getSiblingDB('opp')
const database = db


// --- 1) Catálogo: uf-enem-media (seção estadual) ---
const indicators = [
  {"_id": "uf-enem-media", "label": "Pontuação média no ENEM (áreas objetivas)", "referenceYear": "2024", "unit": "pontos", "description": "Média simples das notas das quatro áreas objetivas do ENEM (Matemática, Linguagens, Ciências da Natureza e Ciências Humanas) entre os participantes da Paraíba. Não inclui a nota de redação, que a fonte não disponibiliza neste recorte.", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "sourceDataset": "inep_enem_observatorio_sebrae", "placements": [{"section": "estadual", "order": 6}]},
]
database.indicators.bulkWrite(indicators.map(i => ({ replaceOne: {
  filter: { _id: i._id }, replacement: i, upsert: true,
} })), { ordered: false })
print(`indicators(estadual) -> ok (${indicators.length} docs)`)

// --- 2) Valores por UF × ano (8 docs) ---
// numericValue = media simples das 4 areas OBJETIVAS. NAO e a nota final do ENEM:
// o cubo nao expoe redacao. O label e a description carregam a ressalva.
// A nota e escala, entao a posicao entre UFs nao e normalizada.
const values = [
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "502,9", "numericValue": 502.9, "referenceYear": "2017", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 505.2, "Linguagens e Códigos": 499.0, "Ciências da Natureza": 500.7, "Ciências Humanas": 506.6}, "participantes": 189876, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 4, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "519,1", "numericValue": 519.07, "referenceYear": "2018", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 523.5, "Linguagens e Códigos": 513.4, "Ciências da Natureza": 482.2, "Ciências Humanas": 557.2}, "participantes": 152049, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 4, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": 3.21, "previousValue": 502.9, "previousYear": "2017", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "495,9", "numericValue": 495.89, "referenceYear": "2019", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 509.8, "Linguagens e Códigos": 510.0, "Ciências da Natureza": 467.8, "Ciências Humanas": 495.9}, "participantes": 147780, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 14, "totalUfs": 27, "entreNordeste": 4, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": -4.47, "previousValue": 519.07, "previousYear": "2018", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "264,8", "numericValue": 264.81, "referenceYear": "2020", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 261.7, "Linguagens e Códigos": 277.9, "Ciências da Natureza": 249.2, "Ciências Humanas": 270.3}, "participantes": 164965, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 1, "totalUfs": 27, "entreNordeste": 1, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": -46.6, "previousValue": 495.89, "previousYear": "2019", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "353,3", "numericValue": 353.34, "referenceYear": "2021", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 360.5, "Linguagens e Códigos": 353.0, "Ciências da Natureza": 333.4, "Ciências Humanas": 366.4}, "participantes": 102002, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 4, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": 33.43, "previousValue": 264.81, "previousYear": "2020", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "368,0", "numericValue": 368.03, "referenceYear": "2022", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 372.0, "Linguagens e Códigos": 373.4, "Ciências da Natureza": 345.5, "Ciências Humanas": 381.2}, "participantes": 103238, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 10, "totalUfs": 27, "entreNordeste": 3, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": 4.16, "previousValue": 353.34, "previousYear": "2021", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "362,2", "numericValue": 362.19, "referenceYear": "2023", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 362.9, "Linguagens e Códigos": 369.9, "Ciências da Natureza": 342.8, "Ciências Humanas": 373.1}, "participantes": 124511, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": -1.59, "previousValue": 368.03, "previousYear": "2022", "basis": "yoy"}},
  {"uf": "25", "indicatorId": "uf-enem-media", "rawValue": "375,1", "numericValue": 375.08, "referenceYear": "2024", "source": "INEP — Microdados do ENEM (cubo INEP_enem), via API Tesseract pública do Observatório Setorial Territorial do Sebrae (observatorio.sebrae.com.br). Média das quatro áreas objetivas; não inclui redação", "isFictional": false, "breakdown": {"porArea": {"Matemática": 375.6, "Linguagens e Códigos": 390.7, "Ciências da Natureza": 353.8, "Ciências Humanas": 380.3}, "participantes": 128546, "composicao": "media simples das 4 areas objetivas — NAO inclui redacao, que o cubo nao expoe", "posicao": {"entreUfs": 12, "totalUfs": 27, "entreNordeste": 5, "totalNordeste": 9, "normalizado": false, "nota": "posicao e comparacao entre pares, nao classificacao — estes indicadores nao tem threshold"}}, "variation": {"deltaPct": 3.56, "previousValue": 362.19, "previousYear": "2023", "basis": "yoy"}},
]
const now = new Date()
const ops = values.map(v => ({ updateOne: {
  filter: { uf: v.uf, indicatorId: v.indicatorId, referenceYear: v.referenceYear },
  update: { $set: Object.assign({}, v, { updatedAt: now }) },
  upsert: true,
} }))
const res = database.stateValues.bulkWrite(ops, { ordered: false })
print(`stateValues -> upserted=${res.upsertedCount} modified=${res.modifiedCount} matched=${res.matchedCount}`)
